name: Cross-Platform PyQt6 Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

jobs:
  test-windows:
    name: Windows Python ${{ matrix.python-version }}
    runs-on: windows-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.11"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Verify PyQt6 installation on Windows
        run: |
          python -c "from PyQt6.QtWidgets import QApplication; print('PyQt6 installation verified on Windows')"
          python -c "from PyQt6.QtCore import QT_VERSION_STR; print(f'Qt version: {QT_VERSION_STR}')"
          python -c "import mdaviz; print('mdaviz imports successfully on Windows')"

      - name: Run basic tests on Windows
        env:
          PYTEST_QT_API: pyqt6
        run: |
          pytest src/tests/test_auto_load.py -v
          pytest src/tests/test_lazy_loading.py -k "not gui" -v

  test-macos:
    name: macOS Python ${{ matrix.python-version }}
    runs-on: macos-latest
    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.11"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Verify PyQt6 installation on macOS
        run: |
          python -c "from PyQt6.QtWidgets import QApplication; print('PyQt6 installation verified on macOS')"
          python -c "from PyQt6.QtCore import QT_VERSION_STR; print(f'Qt version: {QT_VERSION_STR}')"
          python -c "import mdaviz; print('mdaviz imports successfully on macOS')"

      - name: Run basic tests on macOS
        env:
          PYTEST_QT_API: pyqt6
        run: |
          pytest src/tests/test_auto_load.py -v
          pytest src/tests/test_lazy_loading.py -k "not gui" -v

  test-linux-gui:
    name: Linux GUI Tests (PyQt6)
    runs-on: ubuntu-latest
    needs: [test-windows, test-macos]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Install Qt6 and GUI dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            xvfb \
            x11-utils \
            qt6-base-dev \
            qt6-qmake \
            libqt6gui6 \
            libqt6widgets6 \
            libqt6core6 \
            libqt6test6 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-xinerama0 \
            libxcb-xfixes0 \
            libxkbcommon-x11-0 \
            libqt6dbus6 \
            libqt6network6 \
            libqt6opengl6 \
            libqt6svg6 \
            libqt6svgwidgets6

      - name: Install test dependencies
        run: |
          pip install pytest-cov pytest-qt pytest-xvfb

      - name: Run GUI tests with PyQt6
        env:
          QT_QPA_PLATFORM: offscreen
          QT_LOGGING_RULES: "qt.qpa.*=false"
          DISPLAY: ":99.0"
          PYTEST_QT_API: pyqt6
        run: |
          xvfb-run -a pytest src/tests/ --cov=src/mdaviz --cov-report=xml --cov-report=term-missing -v 